### ISSUE TITLE
hello, Is it possible to convert to a static library in C++

### ISSUE THREAD

**Issue by mojie126** [cubicibo/SUPer#10]
Is it possible to convert to a static library in C++? For example, the .a file under mingw32

**Comment by cubicibo** [comment]
Hi,
Unfortunately, SUPer is exclusively Python code. I don't think it is possible to build that as a static library. The released executable runs Python code that is packed with a portable Python dll and all dependencies. Furthermore, there are DLL dependencies in the package that prevent to build it as a static library in any case.

I recommend to build supercli.py as an .exe  with PyInstaller and call it from you C++ program as a [subprocess](https://github.com/benman64/subprocess). It should be good enough.
You can reduce the exe file by removing optional dependencies like guizero and tqdm. You may further drop cv2 if you do some code change in optim.py to only use PILIQ as the quantization mode.

**Comment by mojie126** [comment]
Okay, I understand
