### ISSUE TITLE
File "SUPer\filestreams.py", line 426, in format ValueError: invalid literal for int() with base 10: '1920x800'

### ISSUE THREAD

**Issue by vt-idiot** [cubicibo/SUPer#32]
**I know I am trying to create a "non-compliant" SUP file**

It would be nice to have a flag or option that allows bypassing this.

Use case: re-encoding an anamorphic/letterboxed Blu-Ray to keep a smaller copy on my media server. Most of the time the original PGS/SUP subtitles are deliberately placed entirely within the image area - 1920x800<sup>1</sup> in this case. Reusing the original SUP file results in vertically squished subtitles that are pushed well into the image area in most video players I have tried.

Editing the XML with a script to change the resolution to 1920x800, and offset all of the Y values by -140<sup>1</sup> results in a SUP file that renders exactly as the original did if I resave it using e.g. SubtitleEdit which does not complain if you try to save something non-compliant. For whatever reason, SE's SUP file output is always ~10-20% larger than the original even with no changes made, I wanted to see how the output from this would work out.

**1** Looking at the output XML for this particular movie, it's obvious that all of the subtitle elements were within the image area, as none of the `Graphic Height` + `Graphic Y` results give a value greater than 800, nor are any of the `Graphic Y` values less than 0

**Comment by cubicibo** [comment]
Hi,

I already got similar requests in the past, and I am really torn on the matter. The entirety of SUPer codebase is designed to produce strictly compliant output, with due respect to Blu-ray standard constraints. Any arbitrary ("non-compliant") video format invalidates all of these constraints: most of the codebase becomes irrelevant. There is no longer any point in computing the decoding delay between packets, filtering out "impossible" events, and so on.

Around v0.2.1 release, I had received a complaint from one authoring company that it _was_ possible to produce non-compliant files: it was unacceptable to them.

Given your goal, SUPer is probably not the right software. On the other hand, other HDMV PGS encoders are generall bad and broken... so here's how to achieve what you want:
- Install SUPer in dev mode with pip (`python3 -m pip install -e ./SUPer`)
- Modify the `VideoFormat` enumeration in `utils.py` and append your special format (i.e `HD2P4 = (1920, 800)`)
- Execute the cli or the gui via (`python3 supercli.py [...]` or `python3 supergui.py`). 1920x800 will be supported.

**Comment by KSSW** [comment]
Hello，cubicibo
Nice to see you again
Can I talk about how SUP files are generated in your program as a side note
It relies on that program

I want to be inspired by you
I am writing my own program

Specify external image PNG
Specify time INTC OutTC SRT subtitle time format
Then generate sup subtitle files

**Comment by cubicibo** [comment]
@KSSW Please do not hijack open issues with off-topic requests. Rather, submit it on the forums by private message.
