### ISSUE TITLE
Handling shadows in subtitles

### ISSUE THREAD

**Issue by JenPho** [cubicibo/SUPer#5]
Hi, I found this app usable and out of the other two applications that I stumbled upon, actually worked. (I struggled to get others to compile), however, I either ran into a bug or my misunderstanding of how PGS subtitles actually work. I have image subtitles I rendered in a browser and they have a translucent shadow added. 

The image is cropped to a point where it's pretty much the text and shadow contained, but the image that's placed onto the video is different than my source image because the shadow reaches the edges of the image. It looks fine without the shadow added in, however. I add the subtitles in with ffmpeg and I'm 99% sure ffmpeg does no re-encoding to the subtitles.

In addition, colorspace doesn't seem to matter, no matter which one I choose, the shadows always somehow reach the edge of my video, the subtitles I made though are in bt2020. Here is the [problematic SUP file](https://github.com/JenPho/a/raw/main/ok.sup).

Image without shadow + with pgs onto green video (yes, the text is supposed to look like that, I replaced the japanese text with placeholder text):
![00000001](https://github.com/cubicibo/SUPer/assets/107659428/9da369c5-35fe-4c2a-a816-1aeaa8f4d860)
![image](https://github.com/cubicibo/SUPer/assets/107659428/9dbf8ef5-6318-430a-b583-8b6c7fb6c770)

It's kinda hard to see, but there's a darker box around the text:
![image](https://github.com/cubicibo/SUPer/assets/107659428/dfe76ca4-4390-489b-be27-274cbba706ee)

Image with shadow + with pgs onto green video (note the lack of a 'black box'):
![00000001](https://github.com/cubicibo/SUPer/assets/107659428/55f675ff-360d-48f7-b645-70d2a3e4a8ee)
![image](https://github.com/cubicibo/SUPer/assets/107659428/940e2811-0006-4cfa-83bb-23edad9f5246)

BDN test XML, if it matters (1x1 image prevents subtitles from playing early in VLC while testing):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<BDN Version="0.93" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BD-03-006-0093b BDN File Format.xsd">
  <Description>
    <Name Title="Undefined" Content=""/>
    <Language Code="und"/>
    <Format VideoFormat="1080p" FrameRate="23.976" DropFrame="False"/>
    <Events LastEventOutTC="00:00:16:23" FirstEventInTC="00:00:00:01" ContentInTC="00:00:00:01" ContentOutTC="00:00:16:23" NumberofEvents="2" Type="Graphic"/>
  </Description>
  <Events>
    <Event Forced="False" InTC="00:00:00:01" OutTC="00:00:12:16">
      <Graphic Width="1" Height="1" X="1720" Y="65">00000000.png</Graphic>
    </Event>
    <Event Forced="False" InTC="00:00:12:16" OutTC="00:00:16:23">
      <Graphic Width="90" Height="317" X="1720" Y="65">00000001.png</Graphic>
    </Event>
  </Events>
</BDN>
```

SUPer settings (or at least what I remembered what I ticked):
![image](https://github.com/cubicibo/SUPer/assets/107659428/e8781f04-a731-43eb-915e-0740b1a0513b)

**Comment by cubicibo** [comment]
Hi,
Thank you for the detailed report and the samples.

The shadow box is an issue I've seen too. It comes from Pillow (PIL) quantization process with highly transparent areas. See open issue: https://github.com/python-pillow/Pillow/issues/5204

The current work-around is to select "K-Means (best, slow)" as a quantizer in the GUI. It is very slow but you can use it to produce your final file, while PIL is useful to get a quick output for checking.

In the near future:
- I plan to add libimagequant support in SUPer. It is available in the last commit made in main for Windows x64. Unfortunately macOS is giving me a headache.
- I will add a passthrough for already paletted images. You could use pngquant to palettize your images to 255 colors then execute SUPer and it would use them as is, without additional processing (unless there's an animation).
- I will improve the PIL+KMeans mode to catch failed PIL quantizations and fall-back to K-Means more often.

~~Also a note, if you use ass2bdnxml to generate the input BDN, you must tick the NTSC checkbox whenever the framerate has decimals. Else there will be a drift.~~

**Comment by cubicibo** [comment]
Using your source files, I re-generated the SUP file with each possible quantization option and overlaid it on a white background video. I can confirm that the "K-Means" quantization mode solves the issue for macOS. Windows x64 also has a second alternative with libimagequant.
![comparison](https://github.com/cubicibo/SUPer/assets/55701024/a667df89-5499-4743-b748-c1d52ef65c21)

As this example shows, Pillow RGBA quantize function can produce catastrophic results. Ideally PIL would be removed from SUPer in the future, or at least not offered by default at all. I will try to set this as a goal for v0.2.0.

**Comment by cubicibo** [comment]
[SUPer v0.2.0](https://github.com/cubicibo/SUPer/releases/tag/v0.2.0) fixes the issue entirely. macOS binary will be made available later today.

Closing the issue.
