### ISSUE TITLE
Won't work with utf-8 bom encoded bdn/xml input

### ISSUE THREAD

**Issue by nautilus7** [cubicibo/SUPer#8]
Hi, thanks for the great program.

bdn/xml files produced with subtitleedit are encoded in utf-8 with bom. These files cannot be used (as they are) in SUPer. See the error below:

```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "supergui.py", line 177, in from_bdnxml
  File "SUPer\interface.py", line 49, in optimise
  File "SUPer\filestreams.py", line 462, in __init__
  File "SUPer\filestreams.py", line 465, in parse
  File "SUPer\filestreams.py", line 473, in parse_header
  File "xml\etree\ElementTree.py", line 1338, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
```

This xml file starts with:

`<?xml version="1.0" encoding="utf-8"?>
`

I even tried to change the encoding to:

`<?xml version="1.0" encoding="utf-8-sig"?>
`

but that didn't work as well.

The only way to make this file work is to save as utf-8 in a text editor.

It seems that python's xml parser cannot deal with files encoded in utf-8 with bom. Only  plain utf-8 work.
I also read that[ it's not recommended to encode utf-8 with bom](https://stackoverflow.com/a/2223926/1370918), so I might need to report this to the subtitleedit author to change his program as well.

Thanks.

**Comment by cubicibo** [comment]
Hi,
I tried to fix this by escaping the file in the past but it may not be enough after all:
https://github.com/cubicibo/SUPer/blob/5109b23b9c995701b16341aa784ceee38a2c86ce/SUPer/filestreams.py#L469

Maybe I will fix it later but frankly, this is more of an issue with SubtitleEdit or Python XML ElementTree parser, not SUPer. For now I would suggest you to convert the file to UTF-8 or use another software to render your subs, like [ass2bdnxml](https://github.com/cubicibo/ass2bdnxml)

**Comment by cubicibo** [comment]
Fixed in master, using "utf-8-sig" decoding for all files (standard UTF-8 will pass through untouched).
